soft_limits:
  eff: [16,16,16,10,10,10,1.3,1.3]

# whole-arm joint_state publisher
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# trajectory controller
trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: [j2n6s200_joint_1, j2n6s200_joint_2, j2n6s200_joint_3,
    j2n6s200_joint_4, j2n6s200_joint_5, j2n6s200_joint_6]
  constraints:
    stopped_velocity_tolerance: 1.0
  gains: # Required because we're controlling a velocity interface
    j2n6s200_joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}

j2n6s200_hand_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: [j2n6s200_joint_finger_1, j2n6s200_joint_finger_2]
  constraints:
    stopped_velocity_tolerance: 1.0
  gains: # Required because we're controlling a velocity interface
    j2n6s200_joint_finger_1: {p: 1,  d: 0, i: 0, i_clamp: 1}
    j2n6s200_joint_finger_2: {p: 1,  d: 0, i: 0, i_clamp: 1}

